name: 🐛 Bug Report
description: Report a bug in the code base.
title: "[🐛 Bug]: "
labels: ["bug"]
projects: ["ptrumpis/3"]
assignees:
  - ptrumpis
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Fill out the following information to help diagnose the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the issue in detail. What did you expect to happen, and what actually happened? You can also attach log files and screenshots.
      placeholder: The application crashes when I called the method...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. First you have to...
        2. Then you need to...
        ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✍️ Provide your system information.

  - type: dropdown
    id: node-version
    attributes:
      label: Node Version
      description: Please select your Node.js version (node -v).
      options:
        - v24
        - v23
        - v22
        - v21
        - v20
        - v19
        - v18
    validations:
      required: true
